# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(765, 773)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mainIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_3.addWidget(self.calendarWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCalendar = QtWidgets.QLabel(self.centralwidget)
        self.labelCalendar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelCalendar.setObjectName("labelCalendar")
        self.horizontalLayout_4.addWidget(self.labelCalendar)
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelDate.setText("")
        self.labelDate.setObjectName("labelDate")
        self.horizontalLayout_4.addWidget(self.labelDate)
        self.horizontalLayout_4.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCreateProj = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateProj.setObjectName("btnCreateProj")
        self.horizontalLayout_2.addWidget(self.btnCreateProj)
        self.btnEditProj = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditProj.setObjectName("btnEditProj")
        self.horizontalLayout_2.addWidget(self.btnEditProj)
        self.btnDeleteProj = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteProj.setObjectName("btnDeleteProj")
        self.horizontalLayout_2.addWidget(self.btnDeleteProj)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelProjects = QtWidgets.QLabel(self.centralwidget)
        self.labelProjects.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelProjects.setObjectName("labelProjects")
        self.verticalLayout.addWidget(self.labelProjects)
        self.listWidget_Projects = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Projects.setObjectName("listWidget_Projects")
        self.verticalLayout.addWidget(self.listWidget_Projects)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setInputMask("")
        self.lineSearch.setText("")
        self.lineSearch.setObjectName("lineSearch")
        self.horizontalLayout.addWidget(self.lineSearch)
        self.btnSearch = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.btnCreateTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateTask.setObjectName("btnCreateTask")
        self.horizontalLayout.addWidget(self.btnCreateTask)
        self.btnEditTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditTask.setObjectName("btnEditTask")
        self.horizontalLayout.addWidget(self.btnEditTask)
        self.btnDeleteTask = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeleteTask.setObjectName("btnDeleteTask")
        self.horizontalLayout.addWidget(self.btnDeleteTask)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.labelTasks = QtWidgets.QLabel(self.centralwidget)
        self.labelTasks.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.labelTasks.setObjectName("labelTasks")
        self.verticalLayout_2.addWidget(self.labelTasks)
        self.listWidget_Tasks = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Tasks.setObjectName("listWidget_Tasks")
        self.verticalLayout_2.addWidget(self.listWidget_Tasks)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Task Manager"))
        self.labelCalendar.setText(_translate("MainWindow", "Today is :"))
        self.btnCreateProj.setText(_translate("MainWindow", "Create"))
        self.btnEditProj.setText(_translate("MainWindow", "Edit"))
        self.btnDeleteProj.setText(_translate("MainWindow", "Delete"))
        self.labelProjects.setText(_translate("MainWindow", "Projects:"))
        self.btnSearch.setText(_translate("MainWindow", "Search"))
        self.btnCreateTask.setText(_translate("MainWindow", "Create"))
        self.btnEditTask.setText(_translate("MainWindow", "Edit"))
        self.btnDeleteTask.setText(_translate("MainWindow", "Delete"))
        self.labelTasks.setText(_translate("MainWindow", "Tasks:"))
